services:
  frontend:
    image: node:lts
    volumes:
      - ./frontend:/frontend
    ports:
      - "4200:4200"
      - "49153:49153"
    command: bash -c "cd /frontend && npm i -g @angular/cli && npm i && ng serve --host 0.0.0.0 --watch --poll 500"

  fake-probe-service:
    image: node:lts
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
    volumes:
      - ./backend/fake-probe-service:/backend
    command: bash -c "cd /backend && npm i && npm run start"
    ports:
      - "3001:3000"

  filtering-service:
    image: node:lts
    environment:
      BACKEND_DB_USERNAME: ${BACKEND_DB_USERNAME:-root}
      BACKEND_DB_PASSWORD: ${BACKEND_DB_PASSWORD:-db_pass}
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-secret}
    volumes:
      - ./backend/filtering-service:/backend
    command: bash -c "cd /backend && npm i && npm run start"
    ports:
      - "3002:3000"

  users-service:
    image: node:lts
    environment:
      JWT_SECRET: ${JWT_SECRET:-secret}
      BACKEND_DB_USERNAME: ${BACKEND_DB_USERNAME:-root}
      BACKEND_DB_PASSWORD: ${BACKEND_DB_PASSWORD:-db_pass}
    volumes:
      - ./backend/users-service:/backend
    command: bash -c "cd /backend && npm i && npm run start"
    ports:
      - "3003:3000"

  db:
    image: mariadb:lts
    command: --init-file /data/init.sql
    volumes:
      - ./docker-data/db/init.sql:/data/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-db_pass}

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
    volumes:
      - ./docker-data/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
